#!/bin/sh

adduser --system --home /var/lib/centreon --group centreon
adduser centreon centreon-broker

chown -R www-data:centreon /usr/share/centreon /etc/centreon /var/log/centreon
chmod g+w /usr/share/centreon/www
chmod g+w /usr/share/centreon/filesUpload
chmod g+w /usr/share/centreon/installDir

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
  . /usr/share/apache2/apache2-maintscript-helper
  apache2_invoke disconf php7.3
  apache2_invoke enconf php7.3-fpm
  # FIXME: enmod & dismod ?
fi

#DEBHELPER#
