#!/bin/sh

adduser --system --home /var/lib/centreon --group --in-group centreon-broker centreon-web

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
  . /usr/share/apache2/apache2-maintscript-helper
  apache2_invoke enconf php7.1-fpm
  # FIXME: enmod & dismod ?
fi

# FIXME: add date.timezone = Europe/Paris to
# /etc/php/7.3/fpm/conf.d/50-centreon.ini ?




#DEBHELPER#
