#!/bin/sh

adduser --system --home /var/lib/centreon --group centreon
adduser centreon centreon-broker

chown -R centreon:www-data /usr/share/centreon /etc/centreon /var/log/centreon
chmod -R g+w /usr/share/centreon /etc/centreon /var/log/centreon

chown -R centreon-engine:centreon-broker /var/lib/centreon
chmod -R go+w /var/lib/centreon

# FIXME: until we can get those in the centreon-broker and
# centreon-engine packages
chgrp -R www-data /etc/centreon-broker /etc/centreon-engine /var/cache/centreon
chmod -R g+w /etc/centreon-broker /etc/centreon-engine /var/cache/centreon
chmod -R g+w /var/log/centreon-broker

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
  . /usr/share/apache2/apache2-maintscript-helper
  apache2_invoke disconf php7.3
  apache2_invoke enconf php7.3-fpm
  # FIXME: enmod & dismod ?
fi

#DEBHELPER#
